### ISSUE TITLE
Why is not  the SmartYouTubeTv's scrolling animation as smooth as the Google‘s official Youtube TV APP ？

### ISSUE THREAD

**Issue by StaticCoder** [yuliskov/SmartYouTubeTV#634]

**Comment by fgl27** [comment]
Did you enable animation?
They are disabled by default.

**Comment by StaticCoder** [comment]
> Did you enable animation?
> They are disabled by default.
How to enable animation ? I did not find the animation switch in SmartYoube setting options .

**Comment by fgl27** [comment]
I don't know why but @yuliskov removed the feature

As you can see below the line that activates the code is commented out so the feature never shows as a option for you to enable

https://github.com/yuliskov/SmartYouTubeTV/blob/ce903d6368aefda513efec991b1bbde91dc39a88/smartyoutubetv/src/main/java/com/liskovsoft/smartyoutubetv/bootstrap/dialogtweaks/TweaksDialogSource.java#L63

Here he added the feature
https://github.com/yuliskov/SmartYouTubeTV/commit/0fa08397e475438b167da53d96fab1f42cbc02de#diff-8ab8ab45eaf37f6d8a80658ca873c322

here he disabled it
https://github.com/yuliskov/SmartYouTubeTV/commit/51f8cfdd665d4e43bac7fc11a02aca2ad5d6444c#diff-8ab8ab45eaf37f6d8a80658ca873c322

Maybe affects voice search I don't know I don't use that voice feature

but technically works as I have it force enable by default on my personal build, and I have it for ever never stopped working for me I really like it, I'll test later if voice search is affected some how and update here.

**Comment by fgl27** [comment]
Also @yuliskov if is possible to run a specific css like you run `0_ui_tweaks.css`, make a css that contain the bellow change and run it when `prefs.getEnableAnimatedUI() = true`

```css
/* Force enable side pannel animations*/
.exp-enable-zylon-left-nav .ytlr-surface-page,
.ytlr-tv-secondary-nav-renderer--with-side-nav,
.ytlr-tv-secondary-nav-renderer__nav-container,
.ytlr-tv-secondary-nav-renderer__content {
    transition: transform 200ms cubic-bezier(0.4, 0, 0.2, 1) 0s;
}
```


This way the app will have full animation included side panel.
